[package]
name = "cache"
description = "An arena allocator that can be cached to/from disk."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = ["io"]
io = []

[dependencies]

# We use wee_alloc for wasm "virtual" allocations, since wasm doesn't have
# a built-in mmap or VirtualAlloc equivalent. This adds about 800B to the binary.
# We could alternatively just always grow the heap and leak.
[target.'cfg(target_arch = "wasm32")'.dependencies.wee_alloc]
version = "0.4.5"
default-features = false

[dev-dependencies]
