[package]
name = "roc_can2"
description = "Canonicalize a roc parse IR, resolving names and preparing for type unification."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_collections = { path = "../collections" }
roc_error_macros = { path = "../../error_macros" }
roc_parse = { path = "../parse" }
bumpalo.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
